1:
    base: XLM
    base_issuer: 
    counter: BTC
    counter_issuer: GATEMHCCKCY67ZUCKTROYN24ZYT5GK4EQZ65JJLDHKHRUZI3EUEKMTCH
2:
    base: XLM
    base_issuer: 
    counter: CNY
    counter_issuer: GAREELUB43IRHWEASCFBLKHURCGMHE5IF6XSE7EXDLACYHGRHM43RFOX
3:
    base: XLM
    base_issuer: 
    counter: EURT
    counter_issuer: GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S
4:
    base: XLM
    base_issuer: 
    counter: PHP
    counter_issuer: GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP
5:
    base: XLM
    base_issuer: 
    counter: JPY
    counter_issuer: GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM
6: 
    base: XLM
    base_issuer:
    counter: XRP
    counter_issuer: GA7FCCMTTSUIC37PODEL6EOOSPDRILP6OQI5FWCWDDVDBLJV72W6RINZ
